attention_head_size: 4
categorical_groups: {}
causal_attention: true
dataset_parameters:
  add_encoder_length: true
  add_relative_time_idx: false
  add_target_scales: false
  allow_missing_timesteps: false
  categorical_encoders:
    __group_id__group_id: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        ? !!python/object/apply:numpy.core.multiarray.scalar
        - &id001 !!python/object/apply:numpy.dtype
          args:
          - i8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          AAAAAAAAAAA=
        : 0
      classes_vector_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - &id002 !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id001
        - false
        - !!binary |
          AAAAAAAAAAA=
      warn: true
  constant_fill_strategy: null
  group_ids:
  - group_id
  lags: null
  max_encoder_length: 12
  max_prediction_length: 7
  min_encoder_length: 6
  min_prediction_idx: !!python/object/apply:numpy.core.multiarray.scalar
  - !!python/object/apply:numpy.dtype
    args:
    - i4
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    AAAAAA==
  min_prediction_length: 1
  predict_mode: false
  randomize_length: null
  scalers:
    encoder_length: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.6.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - &id004 !!python/object/apply:numpy.dtype
          args:
          - O8
          - false
          - true
          state: !!python/tuple
          - 3
          - '|'
          - null
          - null
          - null
          - -1
          - -1
          - 63
        - false
        - - encoder_length
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - &id003 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - false
        - !!binary |
          AAAAAAAAAAA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        Bw4AAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAA8D8=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAAAAA=
      with_mean: true
      with_std: true
    precipitation_sum: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.6.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - precipitation_sum
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          0thRwUs1AkA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        Bw4AAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          3CkB0b0xHUA=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          oSGIXHWiSkA=
      with_mean: true
      with_std: true
    rain_sum: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.6.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - rain_sum
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          D7dJu/5SAUA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        Bw4AAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          /tcb1oaMHEA=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          YVS6FFV4SUA=
      with_mean: true
      with_std: true
    temperature_2m_mean: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.6.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - temperature_2m_mean
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          iKqh8txXMEA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        Bw4AAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          UIwiuz/5H0A=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          oSbi4oDyT0A=
      with_mean: true
      with_std: true
  static_categoricals: null
  static_reals: null
  target: Total HPP
  target_normalizer: &id005 !!python/object:pytorch_forecasting.data.encoders.TorchNormalizer
    _method_kwargs: {}
    center: true
    center_: !!python/object/apply:numpy.core.multiarray.scalar
    - *id003
    - !!binary |
      FkJXCF1BeEA=
    method: standard
    method_kwargs: null
    scale_: !!python/object/apply:numpy.core.multiarray.scalar
    - *id003
    - !!binary |
      YhzPoXwec0A=
    transformation: null
  time_idx: time_idx
  time_varying_known_categoricals: null
  time_varying_known_reals:
  - temperature_2m_mean
  - precipitation_sum
  - rain_sum
  time_varying_unknown_categoricals: null
  time_varying_unknown_reals:
  - Total HPP
  variable_groups: null
  weight: null
dropout: 0.1
embedding_labels: {}
embedding_paddings: []
embedding_sizes: {}
hidden_continuous_size: 16
hidden_continuous_sizes: {}
hidden_size: 32
learning_rate: 0.03
log_gradient_flow: false
log_interval: -1
log_val_interval: null
lstm_layers: 1
max_encoder_length: 12
monotone_constaints: {}
monotone_constraints: {}
optimizer: Adam
optimizer_params: null
output_size: 1
output_transformer: *id005
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 1000
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: []
static_reals:
- encoder_length
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- temperature_2m_mean
- precipitation_sum
- rain_sum
time_varying_reals_encoder:
- temperature_2m_mean
- precipitation_sum
- rain_sum
- Total HPP
weight_decay: 0.0
x_categoricals: []
x_reals:
- encoder_length
- temperature_2m_mean
- precipitation_sum
- rain_sum
- Total HPP
